#!/bin/sh

rm -rf reproducible-signal
rm -rf Signal-Android
rm -rf disorderfs_root/
# yes | docker system prune -a


rm -rf .dmypy.json .mypy_cache .pytest_cache .ropeproject
rm -rf cov_html comparators/androguard.db*